name: DynLearn

channels:
  - sys-bio
  - conda-forge

dependencies:

  # System
  - python==3.7.12
  - pip>=21.3.1
  - jupyter>=1.0.0
  - bumpversion>=0.5.3

  # Scientific
  - numpy>=1.21.4
  - scipy>=1.7.3
  - matplotlib>=3.5.0
  - plotly>=2.0.12

  # Machine learning
  # Change to tensorflow if you do not have a GPU
  - tensorflow-gpu<2.0.0

  # Simulation
  - pip:
    - tellurium>=1.3.4
    - libroadrunner>=1.4.6
    - -e .
