name: DynLearn

channels:
  - sys-bio
  - conda-forge

dependencies:

  # System
  - python==3.7.12
  - pip>=21.3.1
  - flake8>=4.0.1
  - pep8>=1.7.1
  - autopep8>=1.6.0
  - jupyter>=1.0.0
  - bumpversion>=0.5.3

  # Scientific
  - numpy>=1.21.4
  - scipy>=1.7.3
  - matplotlib>=3.5.0
  - altair>=4.1.0
  - altair_saver>=0.5.0
  - plotly>=2.0.12

  # Machine learning
  # Change to tensorflow if you do not have a GPU
  - tensorflow-gpu<2.0.0

  # Simulation and optimisation pip packages
  - pip:
    - tellurium>=1.3.4
    - libroadrunner>=2.1.3
    - GPy>=1.10.0
    - GPyOpt>=1.2.6
    - -e .
