#!/bin/bash -ex

for SEED in 39 40 41
do
  scripts/dynlearn-demo --seed $SEED --num-epochs 40 random
  scripts/dynlearn-demo --seed $SEED --num-epochs 30 Bayesian
  scripts/dynlearn-demo --seed $SEED --num-epochs 20 Powell
  scripts/dynlearn-demo --seed $SEED --num-epochs 10 active
done
