#!/bin/bash -e
#
# Script to submit Nanog demo to HPC with different seeds
#

SEED=100
while [ $SEED -le 150 ]
do
  echo " $SEED "
  sbatch ./demo-nanog --seed=$SEED --num-epochs=20
  let SEED++
done
